### ISSUE TITLE
[Question] Using `RootLayout` instead of `GridLayout` in `AppComponent`

### ISSUE THREAD

**Issue by csimpi** [nstudio/xplat#279]
I'm wondering if `RootLayout` should be the default Layout when generating a new nativescript app.
If I'm not wrong it's easy to manage by changing `/packages/nativescript-angular/src/schematics/application/_skipxplat_files/src/app/app.component.html` template file.
LMK if you think it's a good idea, I can even make a PR if that's helpful for you.

**Comment by NathanWalker** [comment]
I love RootLayout myself. Decisions like that are always tough with generation tools since one case may not fit another so probably best to leave the generation a bit more generic I think. The thin line and temptation is to always do more with the generation as I often want to do. Thanks for the notion and offer here though.
