### ISSUE TITLE
Hooks needed for component scss-files

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat#38]
Hi @NathanWalker,

We're using `scss` for our shared components.
This gives us some problems during the bundling process, since `nativescript-dev-sass` only compiles the scss-files in the `app`-folder.

We've solved this by making this before-prepare script:
```javascript
const converter = require('nativescript-dev-sass/lib/converter');
const path = require('path');
const rootPkg = require('../../../../package.json');

module.exports = function($logger, $projectData) {
  const nodeModulesPath = path.join($projectData.projectDir, 'node_modules');
  const prefix = `@${rootPkg.name}`;
  const prefixModulePath = path.join(nodeModulesPath, prefix, 'nativescript');
  return converter.convert($logger, $projectData.projectDir, prefixModulePath, $projectData.appResourcesDirectoryPath);
};
```

watch-hook (only needed for non-bundle builds):
```javascript
const converter = require('nativescript-dev-sass/lib/converter');
const path = require('path');
const rootPkg = require('../../../../package.json');

module.exports = function($logger, $projectData, hookArgs) {
	if (hookArgs.config) {
		const appFilesUpdaterOptions = hookArgs.config.appFilesUpdaterOptions;
		if (appFilesUpdaterOptions.bundle) {
			$logger.warn("Hook skipped because bundling is in progress.")
			return;
		}
	}

  const nodeModulesPath = path.join($projectData.projectDir, 'node_modules');
  const prefix = `@${rootPkg.name}`;
  const prefixModulePath = path.join(nodeModulesPath, prefix, 'nativescript');
  return converter.convert($logger, $projectData.projectDir, prefixModulePath, $projectData.appResourcesDirectoryPath, { watch: true });
}
```

We've run into this problem after we started using the unit tests for nativescript, when we switched the `styleUrls` from `*.component.scss` to `*.component.css`. 

I'm making a PR for this.

**Comment by NathanWalker** [comment]
@m-abs I've seen some troubling issues when nativescript-dev-sass is brought in alongside the bundling builds however I haven't tested that in several months so maybe it's solved in latest. You can try it locally and see if it interferes with local dev or release builds and if clear on your end we can consider it.
Basically it would interfere with the livesync hook processing since it brings in it's own. Perhaps the fix could be done in nativescript-dev-sass plugin to ultimately solve so they could coexist (webpack bundilng and nativescript-dev-sass).

**Comment by m-abs** [comment]
Hi @NathanWalker

The `nativescript-dev-sass` watch-hook skips on bundle builds, so it shouldn't be a problem.

**Comment by NathanWalker** [comment]
Closing since webpack can be configured to handle this.
