### ISSUE TITLE
Question: Migration strategy for existing Angular CLI project with shared code?

### ISSUE THREAD

**Issue by KeithGillette** [nstudio/xplat#43]
I don't see anything obvious in the Nx or xplat documentation, so I'm curious if there is a best practices guide or set of migration tools that would ease the pain of:

1. Adding Nx + xplat to an existing Angular CLI web application
2. Converting existing shared code into Nx libs without having to manually update all imports

**Comment by NathanWalker** [comment]
Hi @KeithGillette as far as #1 you should be able to migrate your standard cli web app to Nx with:
`ng add @nrwl/schematics`

Regarding #2, I've tossed around the idea of migration scripts with xplat which would allow however given the wildly diverse approaches out there folks have taken with shared code it would be pretty difficult to have a script that would get it right for you everytime depending on your original setup. For time being since you know your code best probably more reliable to find/replace imports based on your knowledge of your project.

**Comment by vance** [comment]
In the middle of this right now. The only real approach is to use angular console/cli to generate the components, then copy your business logic and tests in. It is quite tedious, but I see no way around it. If you made the original app entirely with angular CLI, maybe 1 is feasible.

**Comment by KeithGillette** [comment]
Thanks for the guidance. If I come up with any time-saving shortcuts during our migration, I'll post them.
