### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dungahk** [nstudio/xplat#95]
I created a new Nx workspace then added the xplat platforms for web, NativeScript, Electron, and Nest, then generated a web app but when I try to run the app it errors out because it is missing the following dependencies:

- @nrwl/nx
- @ngrx/effects
- @ngrx/router-store
- @ngrx/store
- @project-scope/scss": "file:libs/scss",

Is that expected?

Thanks

**Comment by dungahk** [comment]
If I'm not mistaken this will be closed by #100

**Comment by NathanWalker** [comment]
@dungahk this is actually related to fact that `npm install` does not get called automatically after generating `xplat` and/or other apps. So generally you'd need to run `npm install` after generating. A package install task could be added -- one was never added originally generally because we wanted to leave up to developer to continue adjusting their dependencies if needed.

However it may make sense to have it auto install after generation regardless. Thoughts? Feel free to post a PR regarding this if you'd like.

**Comment by sebastiandg7** [comment]
I'm having the same issue with a fresh installed nx/xplat workspace. The problem seems to be that peer dependencies are not being installed:  

➜ npm i                     
npm WARN @ngrx/effects@7.3.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@7.3.0 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@7.3.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/router-store@7.3.0 requires a peer of @angular/router@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/store@7.3.0 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-translate/core@11.0.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-translate/http-loader@4.0.0 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nrwl/nx@7.7.2 requires a peer of jasmine-marbles@0.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/platform-browser-dynamic@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/common@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/compiler@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/core@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/forms@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/http@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/platform-browser@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of @angular/router@~7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of typescript@~3.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN nativescript-angular@7.2.3 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Preview
￼

audited 17668 packages in 3.292s
found 0 vulnerabilities

**Comment by sebastiandg7** [comment]
@NathanWalker Here is a GIF describing the fresh nx/xplat project described above https://gofile.io/?c=Ct7S00.

There is also another error: when trying to add a web app it los for the file from the root path as shown here: https://gofile.io/?c=zdqjTW

**Comment by dungahk** [comment]
Yes @sebastiandg7 if you try to create a nativescript app without creating an web app before you will get a lot of missing dependencies. I spent some time trying to fix that but I ran out of time :/

**Comment by sebastiandg7** [comment]
Thanks @dungahk What about the issue in the second GIF of my previous comment? I'm not being able to create a web app.

**Comment by dungahk** [comment]
Was that before or after creating the nativescript app?

**Comment by NathanWalker** [comment]
@sebastiandg7 I see. That's with the brand new Nx changes - You chose **empty** during workspace creation. Instead choose 'Angular'. 

We'll update a few things to handle the **empty** case but for now choose 'Angular'.

**Comment by dungahk** [comment]
That was probably the same issue I faced, I created an empty workspace as well. Might be worth adding those bits on the docs.

**Comment by sebastiandg7** [comment]
@NathanWalker Thanks a lot for the clarification. Agreed with @dungahk about adding those couple of points in the docs, at least until improvements are included. Keep it up!

**Comment by NathanWalker** [comment]
This is fixed in `7.4.5` now 👍
